### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by AnshuPathak-88825** [AnshuPathak-88825/Live-code#2]
![Screenshot from 2023-10-01 01-23-24](https://github.com/AnshuPathak-88825/Live-code/assets/78332454/c23fc90c-5654-420b-9fdb-0abca9380a58)
replace current logo with this logo

**Comment by ojKunal** [comment]
Please assign this issue to me ...

**Comment by AnshuPathak-88825** [comment]
I'm assigning issue to you replaced current image with any of these logo 
![image](https://github.com/AnshuPathak-88825/Live-code/assets/78332454/32d0335c-58fd-41c9-a91c-0bb541ae0ea6)
![image](https://github.com/AnshuPathak-88825/Live-code/assets/78332454/ac80854e-a8b5-4755-9a0d-ded79d1df615)

**Comment by rohan-shaw** [comment]
Can you please add hacktober accepted label to my pr

**Comment by AnshuPathak-88825** [comment]
already added

**Comment by rohan-shaw** [comment]
> @rohan-shaw already added

It's not counted as hacktober fest PR

![image](https://github.com/AnshuPathak-88825/Live-code/assets/140471878/100236be-1388-40ba-af58-aaf1c5174afd)
